version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "db_volue:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: tester
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: extractor-worker-db

volumes:
  db_volue:
